application: studly-manager 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: studly.app

- url: /android
  static_dir: android

- url: /calsync
  static_dir: calsync

libraries:
- name: webapp2
  version: latest


