application: studly-manager 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /groups
  static_files: view/groups.html
  upload: view/groups.html

- url: /calsync
  static_dir: calsync

- url: /.*
  script: studly.app

libraries:
- name: webapp2
  version: latest
